### ISSUE TITLE
How to download the aligned fasta files from Pfam database?

### ISSUE THREAD

**Issue by psp3dcg** [Bitbol-Lab/Iterative_masking#1]
Thanks for the really nice package!
However, when I want to test the package on more Pfam data, the downloaded fasta file from InterPro (https://www.ebi.ac.uk/interpro/entry/pfam/#table) is not aligned. For example (PF00020)
>A0A060W133|unreviewed|Tumor necrosis factor receptor superfamily member 6|taxID:8022
MNKYTFLYILCILCTVRLTTPFNAERSSQDILITSKLRTKRQSCQDGTYQHEGMACCLCAAGQHLESHCSVSPEDGTCVY
CEENRTYNSDPNSLDSCEPCTSCDSKANLEVEDRCTIFKDSVCRCQQGHYCNKGKEHCRACYPCTICSEEGIKVACSATN
NTICHAFKEQGRNLAVVFVLTTVLLVLLVIIYLWRSNKYCFGPNGGLTELPNRSSEEMQPLRGVNLWPHLPDIAKTLGWR
DMKQVAECSGMTHTAIESHQLNFPNDSQEQCSSLLRAWVEKEGMTTASVTLVQTLLRMKKKVKAEDIMAIISNKEDGVTG
QNSGSGQV
>A0A060W225|unreviewed|TNFR-Cys domain-containing protein|taxID:8022
MFDKSMSNIGLHYMVVLLIWALNPMVAAQSGLKLTRTGGSVRNLTQRDISCQENLEYPHDNICCLNCLAGTYVKEYCTRA
LERGTCEACEFDTYTEHGNGLRQCLKCTTCHSDQVTTKACTITQDRECRCKPGSFCAPDQACEVCKKCLRCEENEVRLKN
CTATSNTVCKTRLPAPSTIPGTRPGTADIPLLHALLTPVYYYGLGFYCVLTQ

So how to get the aligned fasta like the example in your package? Thank U~

**Comment by damiano-sg** [comment]
Hi, sorry for the delay. From InterPro it's possible to download also the full alignment if you need it. Otherwise you can align it with any HMM of your choice and it should work
